// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_c7Ipcv1xqYTgDljFserfpQh1rJfLWX0',
    appId: '1:564716585518:web:ae1ec71b1781d13c9755bf',
    messagingSenderId: '564716585518',
    projectId: 'daily-pet-island',
    authDomain: 'daily-pet-island.firebaseapp.com',
    storageBucket: 'daily-pet-island.firebasestorage.app',
    measurementId: 'G-C3H7K6MS84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbAKRXs6S74WbbV4bD2XN6zFiK8UUqbwI',
    appId: '1:564716585518:android:867fb5c253fc20a59755bf',
    messagingSenderId: '564716585518',
    projectId: 'daily-pet-island',
    storageBucket: 'daily-pet-island.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARr7dEw_LVbdlkkOVRlqB-0LFcOZvAO7A',
    appId: '1:564716585518:ios:8f00b2e4b05192ff9755bf',
    messagingSenderId: '564716585518',
    projectId: 'daily-pet-island',
    storageBucket: 'daily-pet-island.firebasestorage.app',
    iosBundleId: 'com.dailypet.dailyPetIsland',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARr7dEw_LVbdlkkOVRlqB-0LFcOZvAO7A',
    appId: '1:564716585518:ios:8f00b2e4b05192ff9755bf',
    messagingSenderId: '564716585518',
    projectId: 'daily-pet-island',
    storageBucket: 'daily-pet-island.firebasestorage.app',
    iosBundleId: 'com.dailypet.dailyPetIsland',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_c7Ipcv1xqYTgDljFserfpQh1rJfLWX0',
    appId: '1:564716585518:web:2505d1268d2a32109755bf',
    messagingSenderId: '564716585518',
    projectId: 'daily-pet-island',
    authDomain: 'daily-pet-island.firebaseapp.com',
    storageBucket: 'daily-pet-island.firebasestorage.app',
    measurementId: 'G-YTYSEQ352B',
  );
}
